FROM caddy:builder-alpine AS builder

RUN go env -w GOPROXY=https://goproxy.io,direct \
    && xcaddy build \
    --with github.com/caddy-dns/cloudflare

FROM caddy:alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy