services:
  seaweedfs:
    image: bitnami/seaweedfs:latest
    ports:
      - "9333:9333" #web
      - "8333:8333" #s3
    volumes:
      - ./data:/data
    configs:
      - source: s3.json
        target: /data/s3.json
    command:
      - "server"
      - "-s3"
      - "-s3.config=/data/s3.json"

  s3manager:
    image: cloudlena/s3manager
    ports:
      - "8080:8080"
    environment:
      - ENDPOINT=seaweedfs:8333
      - ACCESS_KEY_ID=myaccesskey
      - SECRET_ACCESS_KEY=myaccesskey
      - USE_SSL=false

configs:
  s3.json:
    content: |
      {
        "identities": [
          {
            "name": "anonymous",
            "actions": [
              "Read"
            ]
          },
          {
            "name": "me",
            "credentials": [
              {
                "accessKey": "myaccesskey",
                "secretKey": "myaccesskey"
              }
            ],
            "actions": [
              "Admin",
              "Read",
              "ReadAcp",
              "List",
              "Tagging",
              "Write",
              "WriteAcp"
            ]
          }
        ]
      }
