name: mihomo

on:
  workflow_dispatch: null
  push:
    branches:
      - 'main'
    paths:
      - 'mihomo/**'
      - '.github/workflows/mihomo_builder.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup ENV
        run: |
          echo owner_lc=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ github.workflow }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ env.owner_lc }}/${{ github.workflow }}:latest
          labels: |
            org.opencontainers.image.documentation=https://github.com/LinuxHub-Group/dockerfiles/blob/main/${{ github.workflow }}/README.md
            org.opencontainers.image.authors=${{ github.repository_owner }}